[package]
name = "boltzmann-solver"
version = "0.1.0"
authors = ["JP-Ellis <josh@jpellis.me>"]
edition = "2018"

[dependencies]
log = "0.4.6"
ndarray = "0.12.1"
quadrature = "0.1.2"
rug = "1.3.0"
special-functions = { git = "https://github.com/hep-rs/special-functions.git" }

[dev-dependencies]
GSL = "1.1.0"
csv = "1.0.7"
itertools = "0.8.0"
num = "0.2.0"

[features]
default = []
nightly = []
