[package]
name = "boltzmann-solver"
version = "0.1.0"
authors = ["JP-Ellis <josh@jpellis.me>"]
edition = "2018"

[dependencies]
log = "0.4"
ndarray = { version = "0.13", features = ["rayon"]}
num-complex = "0.2.3"
quadrature = "0.1"
rayon = "1.1"
special-functions = { git = "https://github.com/hep-rs/special-functions.git" }

serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
chrono = "0.4.6"
csv = "1.0"
fern = { version = "0.5.8", features = ["colored"] }
itertools = "0.8.0"
num = "0.2.0"

[features]
default = []
nightly = []

[profile.test]
opt-level = 1
debug = true