[package]
name = "boltzmann-solver"
version = "0.1.0"
authors = ["JP-Ellis <josh@jpellis.me>"]

[dependencies]
log = "0.4.1"
ndarray = "0.11.2"
quadrature = "0.1.2"
special_functions = { git = "https://github.com/hep-rs/special-functions.git" }

[dev-dependencies]
csv = "1.0.0"

[features]
default = []
nightly = []
strict = []
