[package]
name = "boltzmann-solver"
version = "0.1.0"
authors = ["JP-Ellis <josh@jpellis.me>"]
edition = "2018"

[dependencies]
log = "0.4"
ndarray = { version = "0.13" }
num-complex = "0.2"
quadrature = "0.1"
special-functions = { git = "https://github.com/hep-rs/special-functions.git" }

# Optional dependencies
rayon = { optional = true, version = "1.3" }
serde = { optional = true, version = "1.0", features = ["derive"] }

[dev-dependencies]
chrono = "0.4"
csv = "1.1"
fern = { version = "0.6", features = ["colored"] }
itertools = "0.9"
num = "0.2"
serde_json = "1.0"

[features]
default = ["rk87", "parallel", "serialization"]

nightly = []
serialization = ["serde", "ndarray/serde", "num/serde"]
parallel = ["rayon", "ndarray/rayon"]

rk21 = []
rk32 = []
rk43 = []
rk54 = []
rk65 = []
rk76 = []
rk87 = []
rk98 = []

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3