[package]
name = "boltzmann-solver"
version = "0.1.0"
authors = ["JP-Ellis <josh@jpellis.me>"]

[dependencies]
quadrature = "0.1.2"
special_functions = { path = "../special-functions" }
log = "0.4.1"

[dev-dependencies]
csv = "1.0.0-beta.5"

[features]
default = []
nightly = []
strict = []