[package]
name = "boltzmann-solver"
version = "0.1.0"
authors = ["JP-Ellis <josh@jpellis.me>"]
edition = "2018"

[dependencies]
log = "0.4"
ndarray = { version = "0.13" }
num-complex = "0.2"
quadrature = "0.1"
special-functions = { git = "https://github.com/hep-rs/special-functions.git" }

rayon = { version = "1.3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
chrono = "0.4"
csv = "1.1"
fern = { version = "0.5", features = ["colored"] }
itertools = "0.8"
num = "0.2"
rayon = "1.3"

[features]
default = ["serialization", "parallel"]
# default = []

nightly = []
serialization = ["serde", "ndarray/serde"]
parallel = ["rayon", "ndarray/rayon"]

[profile.test]
opt-level = 1
debug = true