[package]
name = "boltzmann-solver"
version = "0.1.0"
authors = ["JP-Ellis <josh@jpellis.me>"]
edition = "2018"

[dependencies]
log = "0.4"
ndarray = "0.12"
quadrature = "0.1"
rayon = "1.1"
special-functions = { git = "https://github.com/hep-rs/special-functions.git" }

[dev-dependencies]
GSL = "1.1"
csv = "1.0"
itertools = "0.8.0"
num = "0.2.0"
fern = { version = "0.5.8", features = ["colored"] }
chrono = "0.4.6"

[features]
default = []
nightly = []
