[package]
name = "boltzmann-solver"
version = "0.1.0"
authors = ["JP-Ellis <josh@jpellis.me>"]

[dependencies]
log = "0.4.6"
ndarray = "0.12.0"
quadrature = "0.1.2"
special_functions = { git = "https://github.com/hep-rs/special-functions.git" }

[dev-dependencies]
csv = "1.0.2"
num = "0.2.0"
itertools = "0.7.9"

[features]
default = []
nightly = []
strict = []
