(function() {var implementors = {};
implementors["ndarray"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"ndarray/struct.ShapeError.html\" title=\"struct ndarray::ShapeError\">ShapeError</a>",synthetic:false,types:["ndarray::error::ShapeError"]},];
implementors["num_complex"] = [{text:"impl&lt;E:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"num_complex/struct.ParseComplexError.html\" title=\"struct num_complex::ParseComplexError\">ParseComplexError</a>&lt;E&gt;",synthetic:false,types:["num_complex::ParseComplexError"]},];
implementors["rug"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"rug/integer/struct.ParseIntegerError.html\" title=\"struct rug::integer::ParseIntegerError\">ParseIntegerError</a>",synthetic:false,types:["rug::integer::big::ParseIntegerError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"rug/integer/struct.TryFromIntegerError.html\" title=\"struct rug::integer::TryFromIntegerError\">TryFromIntegerError</a>",synthetic:false,types:["rug::integer::TryFromIntegerError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"rug/rational/struct.ParseRationalError.html\" title=\"struct rug::rational::ParseRationalError\">ParseRationalError</a>",synthetic:false,types:["rug::rational::big::ParseRationalError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"rug/rational/struct.TryFromFloatError.html\" title=\"struct rug::rational::TryFromFloatError\">TryFromFloatError</a>",synthetic:false,types:["rug::rational::TryFromFloatError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"rug/float/struct.ParseFloatError.html\" title=\"struct rug::float::ParseFloatError\">ParseFloatError</a>",synthetic:false,types:["rug::float::big::ParseFloatError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"rug/complex/struct.ParseComplexError.html\" title=\"struct rug::complex::ParseComplexError\">ParseComplexError</a>",synthetic:false,types:["rug::complex::big::ParseComplexError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
