name: Rust

on:
  release:
  push:
    paths:
      - "**/*.rs"
      - "Cargo.toml"
  pull_request:
    paths:
      - "**/*.rs"
      - "Cargo.toml"

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        default-features: [true, false]
        toolchain: [stable, beta, nightly]
        include:
          - toolchain: stable
            default-features: true
            features: "serialization parallel"
          - toolchain: beta
            default-features: true
            features: "serialization parallel"
          - toolchain: nightly
            default-features: true
            features: "serialization parallel nightly"
          - toolchain: stable
            default-features: false
            features: ""
          - toolchain: beta
            default-features: false
            features: ""
          - toolchain: nightly
            default-features: false
            features: "nightly"
    steps:
      - uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy
      - name: Format
        # switch to `action-rs/rustfmt-check` once that is available
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: >-
            --
            --check
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: clippy-${{ matrix.toolchain }}-${{ matrix.default-features }}
          args: >-
            --no-default-features
            --features "${{ matrix.features }}"
            --bins
            --examples
            --tests
            --benches

  test:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        default-features: [true, false]
        toolchain: [stable, beta, nightly]
        include:
          - toolchain: stable
            default-features: true
            features: "serialization parallel"
          - toolchain: beta
            default-features: true
            features: "serialization parallel"
          - toolchain: nightly
            default-features: true
            features: "serialization parallel nightly"
          - toolchain: stable
            default-features: false
            features: ""
          - toolchain: beta
            default-features: false
            features: ""
          - toolchain: nightly
            default-features: false
            features: "nightly"
    steps:
      - uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: >-
            --no-default-features
            --features "${{ matrix.features }}"

  test-release:
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        default-features: [true, false]
        include:
          - default-features: true
            features: "serialization parallel"
          - default-features: false
            features: ""
    steps:
      - uses: actions/checkout@v2
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Test (release)
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: >-
            --release
            --no-default-features
            --features "${{ matrix.features }}"
            --
            --test-threads 1
